### ISSUE TITLE
Add comment above metadata

### ISSUE THREAD

**Issue by NikoKrause** [izimobil/polib#103]
Hey, I'm creating a po file from scratch.
As described in the docs, i can add metadata to the po file:
https://polib.readthedocs.io/en/latest/quickstart.html#creating-po-catalogs-from-scratch

This way it creates an empty "#" comment above the metadata. Is there a way to add/change the comment above the metadata? 

Btw the docs seem to still refere to bitbucket, which seem to be dead links.

**Comment by kthy** [comment]
The ["standard" header comments](https://www.gnu.org/software/gettext/manual/html_node/Header-Entry.html#Header-Entry) are

```text
# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR ORGANIZATION
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
```

and are intended to be filled in by hand when using GNU gettext. I might look into a PR that 1) adds these boilerplate comments, and 2) makes them configurable through the polib API.

**Comment by kthy** [comment]
Actually, looking through the code right now you can simply set the comment in `po.header`. But it's inconvenient if you want to follow the GNU gettext format.

**Comment by NikoKrause** [comment]
Thanks, maybe someone wants to add this info in the docs.
