### ISSUE TITLE
Cannot get metadata from existing po

### ISSUE THREAD

**Issue by mathben** [izimobil/polib#109]
```python
import polib
po = polib.POFile()
po.metadata = {
    'Project-Id-Version': '1.0',
    'Report-Msgid-Bugs-To': 'you@example.com',
    'POT-Creation-Date': '2007-10-18 14:00+0100',
    'PO-Revision-Date': '2007-10-18 14:00+0100',
    'Last-Translator': 'you <you@example.com>',
    'Language-Team': 'English <yourteam@example.com>',
    'MIME-Version': '1.0',
    'Content-Type': 'text/plain; charset=utf-8',
    'Content-Transfer-Encoding': '8bit',
}
po.save("/tmp/test.po")
po2 = polib.POFile("/tmp/test.po")
po2.metadata
# return value is {}
```
po2.metadata suppose to return 
 {
    'Project-Id-Version': '1.0',
    'Report-Msgid-Bugs-To': 'you@example.com',
    'POT-Creation-Date': '2007-10-18 14:00+0100',
    'PO-Revision-Date': '2007-10-18 14:00+0100',
    'Last-Translator': 'you <you@example.com>',
    'Language-Team': 'English <yourteam@example.com>',
    'MIME-Version': '1.0',
    'Content-Type': 'text/plain; charset=utf-8',
    'Content-Transfer-Encoding': '8bit',
}

**Comment by Carloswaldo** [comment]
pofile is the function that parses a .po file, POFile is the name of the class. You need to open the file like you did the first time:

```python
po2 = polib.pofile("/tmp/test.po")
```

**Comment by mathben** [comment]
My mistake of copying code, the first time was an error, pofile doesn't exist in polib. I fix the example, the problem is still here.
It's polib.POFile([file_path])

**Comment by Carloswaldo** [comment]
The solution is still the same, you need to open the file using polib.pofile(), it returns a POFile instance:

https://polib.readthedocs.io/en/latest/api.html#the-pofile-function

**Comment by mathben** [comment]
Thanks, it works! :D
