### ISSUE TITLE
Create git tags / github releases for 1.0.8, 1.0.9, 1.1.0, etc...

### ISSUE THREAD

**Issue by MestreLion** [izimobil/polib#99]
Judging from Github, it seems the latest release was 1.0.7 in 2015. Only by going to https://pypi.org/project/polib/ we see there has been progress and Polib is already at 1.1.0. Why not mark the latest release (and possibly the other ones since 1.0.7) with Git Tags and/or Github Releases? This might be as simple as creating git tags in the corresponding commits in any local repository and then pushing them all here.

**Comment by MestreLion** [comment]
Considering this repository has recently moved to Github, I'm willing to provide detailed assistance / instructions on all `git` commands required to create such releases, just let me know if you need / want any help on this!

**Comment by izimobil** [comment]
Done. For some reason release 1.0.9 doesn't exist though.
